from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name = 'home'),
    path('artist_home/', artist_home, name='artist_home'),
    path('artists/', artists, name='artists'),
    path('gallery/', gallery, name='gallery'),
    path('chat/', chat, name='chat'),
    path('add_event/', add_event, name='add_event'),
    path('events/', events, name='events'),
    path('tutorials/', tutorials, name='tutorials'),
    path('portal/', portal, name='portal'),
    path('portal_home/', portal_home, name='portal_home'),
    path('shop/', shop, name='shop'),
    path('chat/<int:id>', chat, name='chat'),
    path('upload/', upload, name='upload'),
    path('uploadmats/', uploadmats, name='uploadmats'),
    path('uploadvideo/', uploadvideo, name='uploadvideo'),
    path('uploadpdf/', uploadpdf, name='uploadpdf'),
    path('user_login/', user_login, name='user_login'),
    path('artist_login/', artist_login, name='artist_login'),
    path('artist_messages/', artist_messages, name='artist_messages'),
    path('user_register/', user_register, name='user_register'),
    path('artist_register/', artist_register, name='artist_register'),
    path('show_art/<str:phone>/',show_art,name="show_art"),
    path('portal_orders/',portal_orders,name='portal_orders'),
    path('artist_orders/',artist_orders,name='artist_orders'),
    path('user_orders/',user_orders,name='user_orders'),
    path('user_chats/',user_chat,name='user_chats'),
    path('query/',query,name="query"),
    path('send_message/<int:id>/', send_message, name='send_message'),
    path('billing/<int:id>/', billing,name="billing"),
    path('logout/', logout, name='logout'),
]