# Generated by Django 5.0.4 on 2024-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0002_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(default='Annonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='query',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
