# Generated by Django 5.0.4 on 2024-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0003_query_email_query_name_query_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
