# Generated by Django 5.0.4 on 2024-04-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0004_review_rating_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaladmin',
            name='name',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
