# Generated by Django 5.0.4 on 2024-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0005_portaladmin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.FileField(default='', upload_to='Events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=50),
        ),
    ]
