# Generated by Django 5.0.4 on 2024-05-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0006_event_date_event_name_event_pic_event_venue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortalAdmin',
            new_name='Portal',
        ),
    ]
