# Generated by Django 5.0.4 on 2024-05-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0007_rename_portaladmin_portal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='passoword',
            new_name='password',
        ),
    ]
