# Generated by Django 5.0.4 on 2024-05-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0008_rename_passoword_portal_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
