# Generated by Django 5.0.4 on 2024-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0009_rename_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='pic',
            field=models.FileField(default='', upload_to='Arts/'),
        ),
    ]
