# Generated by Django 5.0.4 on 2024-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0010_art_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='forsale',
            field=models.BooleanField(default=False),
        ),
    ]
