# Generated by Django 5.0.4 on 2024-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0011_art_forsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.BooleanField(default=True),
        ),
    ]
