# Generated by Django 5.0.4 on 2024-05-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0012_artist_artist_portal_admin_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='recipient_artist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to='aa_app.artist'),
        ),
        migrations.AddField(
            model_name='chat',
            name='recipient_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to='aa_app.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_artist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='aa_app.artist'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Artist')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='aa_app.user'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FileField(default='', upload_to='Payments/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aa_app.art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aa_app.user')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
