# Generated by Django 5.0.4 on 2024-05-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0014_alter_chat_recipient_artist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
