# Generated by Django 5.0.4 on 2024-05-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0016_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created']},
        ),
    ]
