# Generated by Django 5.0.1 on 2026-06-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0020_artist_bio_order_status_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_app.portal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aa_app.artist'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
